#!/bin/bash

help()
{
man "$1" > /dev/null 2>&1 && man tcol || echo tcol: please generate man page
exit
}

# Parse options
options=$(getopt -o h -l help -n "$0" -- "$@") || exit
eval set -- "$options"

while [[ $1 != -- ]]; do
	case $1 in
		-h|--help ) help ;;
		*         ) echo "tdiff: bad option: $1" >&2 ; exit 1;;
	esac
done
shift # --

options="-a --no-color --no-bindings"

if [[ -z "$1" ]] ; then
	paneless $options -c $(dirname $0)/tcol.pless -C 0 -w 100% <(:) -I "1=color_swash" -w 18 <(:) "${@:2}"
elif [[ -f "$1" || -p "$1" ]] ; then
	paneless $options -c $(dirname $0)/tcol.pless -C 0 -w 100% "$1" -I "1=color_swash" -w 18 <(:) "${@:2}"
else
	echo "tcol: input must be a file, try tcol --help" ; exit 1
fi


